# Generated by Django 4.2.4 on 2024-06-28 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='observacion',
            field=models.TextField(blank=True, default='Sin observaciones', null=True),
        ),
    ]
