# Generated by Django 4.2.4 on 2024-07-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_pedido_descuento_pedido_impuesto_pedido_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultima_actividad',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
