# Generated by Django 5.0.7 on 2024-08-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_usuario_ultima_actividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='info_venta_producto_id',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='info_venta_tipo',
        ),
        migrations.AddField(
            model_name='venta',
            name='info_venta_json',
            field=models.JSONField(default='null'),
        ),
    ]
