# Generated by Django 5.0.7 on 2024-08-24 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_remove_venta_info_venta_producto_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='info_venta_json',
            field=models.JSONField(blank=True, default='null', null=True),
        ),
    ]
