# Generated by Django 5.0.7 on 2024-08-25 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_ventaproducto_ventaproveedor_ventatipo_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('aseo', 'Aseo'), ('bebidas', 'Bebidas'), ('carnes', 'Carnes'), ('lacteos', 'Lacteos'), ('pastas', 'Pastas'), ('snacks', 'Snacks'), ('otros', 'Otros')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.categoria'),
        ),
    ]
