# Generated by Django 5.0.7 on 2024-08-25 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_migrate_tipo_to_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
    ]
