# Generated by Django 5.0.7 on 2024-08-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_remove_producto_tipo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VentaTipo',
            new_name='VentaCategoria',
        ),
    ]
