# Generated by Django 5.0.7 on 2024-08-25 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_rename_ventatipo_ventacategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('aseo', 'Aseo'), ('bebidas', 'Bebidas'), ('carnes', 'Carnes'), ('lacteos', 'Lacteos'), ('pastas', 'Pastas'), ('snacks', 'Snacks'), ('otros', 'Otros')], default='otros', max_length=100),
        ),
    ]
