# Generated by Django 5.0.7 on 2024-08-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_categoria_tipo_alter_categoria_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='tipo',
        ),
    ]
