# Generated by Django 5.0.7 on 2024-08-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=255),
        ),
    ]
