# Generated by Django 5.0.7 on 2024-08-27 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_categoria_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventacategoria',
            name='venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.venta'),
        ),
        migrations.AddField(
            model_name='ventaproducto',
            name='venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.venta'),
        ),
        migrations.AddField(
            model_name='ventaproveedor',
            name='venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.venta'),
        ),
    ]
