# Generated by Django 5.0.7 on 2024-08-27 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_ventacategoria_venta_ventaproducto_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventacategoria',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.venta'),
        ),
        migrations.AlterField(
            model_name='ventaproducto',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.venta'),
        ),
        migrations.AlterField(
            model_name='ventaproveedor',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.venta'),
        ),
    ]
