# Generated by Django 5.0.7 on 2024-08-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_alter_ventacategoria_venta_alter_ventaproducto_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventacategoria',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ventaproducto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ventaproveedor',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
