# Generated by Django 5.0.7 on 2024-08-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_ventacategoria_fecha_ventaproducto_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventacategoria',
            name='producto_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventacategoria',
            name='proveedor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventaproducto',
            name='categoria_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventaproducto',
            name='proveedor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventaproveedor',
            name='categoria_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventaproveedor',
            name='producto_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
