# Generated by Django 5.0.7 on 2024-08-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_ventacategoria_producto_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='info_venta_json',
        ),
    ]
