# Generated by Django 5.0.7 on 2024-08-27 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_remove_venta_info_venta_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventacategoria',
            name='producto_id',
        ),
        migrations.RemoveField(
            model_name='ventacategoria',
            name='proveedor_id',
        ),
        migrations.RemoveField(
            model_name='ventaproducto',
            name='categoria_id',
        ),
        migrations.RemoveField(
            model_name='ventaproducto',
            name='proveedor_id',
        ),
        migrations.RemoveField(
            model_name='ventaproveedor',
            name='categoria_id',
        ),
        migrations.RemoveField(
            model_name='ventaproveedor',
            name='producto_id',
        ),
        migrations.AddField(
            model_name='ventacategoria',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.producto'),
        ),
        migrations.AddField(
            model_name='ventacategoria',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.proveedor'),
        ),
        migrations.AddField(
            model_name='ventacategoria',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.seccion'),
        ),
        migrations.AddField(
            model_name='ventaproducto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.categoria'),
        ),
        migrations.AddField(
            model_name='ventaproducto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.proveedor'),
        ),
        migrations.AddField(
            model_name='ventaproducto',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.seccion'),
        ),
        migrations.AddField(
            model_name='ventaproveedor',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.categoria'),
        ),
        migrations.AddField(
            model_name='ventaproveedor',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.producto'),
        ),
        migrations.AddField(
            model_name='ventaproveedor',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.seccion'),
        ),
        migrations.AlterField(
            model_name='ventacategoria',
            name='entidad_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.categoria'),
        ),
        migrations.AlterField(
            model_name='ventaproducto',
            name='entidad_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.producto'),
        ),
        migrations.AlterField(
            model_name='ventaproveedor',
            name='entidad_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.proveedor'),
        ),
        migrations.CreateModel(
            name='VentaSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.categoria')),
                ('entidad_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.seccion')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.proveedor')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.venta')),
            ],
        ),
    ]
