# Generated by Django 5.0.7 on 2024-08-27 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_remove_ventacategoria_producto_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
