# Generated by Django 5.0.7 on 2024-09-03 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_delete_dashboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='stock',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.seccion'),
        ),
        migrations.AddField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
