# Generated by Django 5.0.7 on 2024-09-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_remove_stock_descripcion_stock_seccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='seccion',
        ),
    ]
