# Generated by Django 5.0.7 on 2024-09-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_remove_stock_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
