# Generated by Django 4.2.4 on 2024-05-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_venta_cantidad_remove_venta_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='hash',
            field=models.CharField(default='Sin hash', max_length=255),
        ),
    ]
